### PR TITLE
Add NDBN agency type classification drop down form

### LINKED ISSUE #75: Agency Type Classification

### PR DESCRIPTION
**Pull request by Nirvikalpa108**
Resolves #75 

### Description
We have created a dropdown box allowing agency users to choose which of the National Diaper Bank Network's classifications their agency falls into.

We did this by adding the NDBN's Agency Type classifications to the list of constants in the initialisers directory. 
We then added a helper method to the form to create a dropdown. 

_This issue will be fully resolved when we have learnt whether the "other" classification requires a description from the agency user, as suggested in the excel spreadsheet supplied._

### Type of change
* New feature (non-breaking change which adds functionality)

### How Has This Been Tested?

We tested this by submitting the form and checking in the rails console that the database had attributed this new item of information to the partner.

It would also be good to know (for my learning in particular) if any tests are required for this change? I did check the spec directory, but couldn't find a test for this form, but I could easily have missed this.

Thank you @chaserx for pairing with me on this issue ❤️

### CODE REVIEW

**Comment by Nirvikalpa108** [comment]
Hi @chaserx I got a fail on my Travis CI check. 

Capybara can't find the fill out the partner details. I guess this is the test I should have found in the spec directory, right? Is the test trying to enter text into the old agency type field and it now can't do this, because we've changed it to a dropdown? 

Really excited to understand the test and learn about this, so thanks in advance! 😃

**Comment by seanmarcia** [comment]
Hey @Nirvikalpa108 looks like you moved from a text_field to a select field. You'll need to update the test to reflect that! :)

**Comment by chaserx** [comment]
@Nirvikalpa108 yes you've got it. here are some hints. 

this the relevant test file: https://github.com/rubyforgood/partner/blob/fa1559b7d4b95cc078a8471dbdf2267ef97bf486/spec/features/partner_edit_feature_spec.rb#L1

you'll see the step where it tries to fill out the `partner_agency_type`

replace the method that fills in the field with one that makes a selection from the dropdown

here's some capybara docs: 

https://github.com/teamcapybara/capybara#interacting-with-forms

**Comment by chaserx** [comment]
@Nirvikalpa108 The folks at PDXDiaperBank got back to us in the issue about allowing the user to enter a description if they are an "other" agency type. They would like to have that functionality if possible. We can work on that this week, but until then here's some guidance:

Look into jquery `.change()` method to capture the dropdown selection. 
https://api.jquery.com/

And we'll need a database migration to add the column the 'other_agency_description' or whatever we should call it. https://guides.rubyonrails.org/active_record_migrations.html

**Comment by Nirvikalpa108** [comment]
@seanmarcia @chaserx thanks very much for advising me on how to amend the capybara test so that it passes. I've now submitted an additional commit, which passes the test. 

Grateful for your feedback on the code in case it can be improved in any way. In particular I would like to understand the protocol for choosing which value to pass into the test given there are so many in the NDBN agency list? Is there a way to write a test which randomly picks a key:value pair from the AGENCY_TYPES constants? Grateful for your advice here.

@chaserx thank you SO much for your tip on preparing for the final part of this PR, the option to add an"other" classification. I have started the reading and would be grateful to pair on this or to discuss the steps required via email. Thank you again 😃

**Pull request merged**
