### PR TITLE
[WIP] Add pick up recipients

### LINKED ISSUE #121: Pick Up Recipients
# Summary
Occasionally there is miscommunication or mistakes with the families picking up diapers at partners and periodically someone who the family does not approve up attempts to pick up the diapers. We need a field to list the members of the family who are allowed to pick up their diapers aside from the guardian.

# Criteria for Completion
- [ ] Add a field to the families "Authorized to Pick Up"

### PR DESCRIPTION
**Pull request by GabrielRMuller**
Resolves #121 

### Description
To create an option to add members that are authorized to make pick ups, I've created a new model called `authorized_family_member`. The authorized family member can be registered through the family index view (just like children).

I'm not sure if this is a little more complex than you wanted, but I'm leaving some screenshots so you can see how it looks now. I'm also leaving the tag of [WIP] and if you guys approve the idea, I'll create some specs for it, otherwise you can suggest a more simple change and I can make it as well.

### Type of change

* New feature (non-breaking change which adds functionality)

### Screenshots

image

image

image

### CODE REVIEW

**Comment by benreyn** [comment]
Thanks for the contribution @GabrielRMuller! Ill make sure to give this a thorough review as soon as possible.

**Comment by seanmarcia** [comment]
Hey @GabrielRMuller this is awesome!

Sorry for the delay, our large Ruby for Good event is next week and we've been busy prepping for it!

Aside from the rubocop issues there are one or two things stylistically that I think should be changed:

I love how you added the `Add An Authorized Member To This Family` button! I don't think the authorized family members should have their own menu location. They should only appear on the family show page underneath the family information.

Other than that (and a couple rubocop violations) this looks great!

**Comment by GabrielRMuller** [comment]
oh hey, thanks for checking it! I'll make the changes as soon as I can.

**Comment by seanmarcia** [comment]
Thank you so much for this @GabrielRMuller ! This is perfect!

**Pull request merged**
