### PR TITLE
Adds in UI for flipper

### PR DESCRIPTION
**Pull request by seanmarcia**
You'll need to add the following into your `.env` file:
```
FLIPPER_USERNAME="admin"
FLIPPER_PASSWORD="password"
```

### CODE REVIEW

**Comment by seanmarcia** [comment]
@benreyn

**Comment by benreyn** [comment]
Should we add those ENV variables to our `.env.sample` files to make setup easier for new developers?

**Comment by seanmarcia** [comment]
Ha. I didn't even know who had an `.env.sample`

**Comment by seanmarcia** [comment]
Updated the `.env.sample`

**Pull request merged**
