### PR TITLE
Add spec to PartnerService

### PR DESCRIPTION
**Pull request by EmersonManabuAraki**
###Description
Add new specs to test PartnerService for more test coverage

### Type of change

* Improvement

### How Has This Been Tested?
Running specs

### Screenshots
image

### CODE REVIEW

**Comment by benreyn** [comment]
@EmersonManabuAraki, this looks like it also has the changes from #179 in it. Are you still available to clean this up?

**Comment by EmersonManabuAraki** [comment]
i'm busy recently, i don't know if I'll have time to fix it

**Comment by benreyn** [comment]
Thanks for checking in @EmersonManabuAraki ! No worries, we appreciate your work on this. We'll take this and #216 over for you.

**Comment by sarslanoglu** [comment]
@benreyn I can help here also

**Comment by edwinthinks** [comment]
Hey there @sarslanoglu are you still working on this?

**Comment by sarslanoglu** [comment]
@edwinthinks Completely forgot I wrote here. I was waiting someone is going to assign me or mention me on comments so I could get a notification from Github. If we have time I can add those tests these weekend. If not fell free to take the issue

**Comment by edwinthinks** [comment]
@sarslanoglu sure I can assign you :). No worries at all

**Comment by edwinthinks** [comment]
Thanks for your work. However, I noticed that the service object `PartnerService` is no longer being used in the application. I'll be removing it

**Pull request closed without merging**
