### PR TITLE
Add spec to ChildrenController

### LINKED ISSUE #151: Test Coverage: Children Controller
At 59% coverage, we should increase test coverage for the Children Controller with **request specs**

Screen Shot 2019-07-28 at 9 35 26 AM

### PR DESCRIPTION
**Pull request by EmersonManabuAraki**
Resolves #151 

### Description
Add new spec to test ChildrenController

### Type of change
* Improvement

### How Has This Been Tested?
Running specs

### Screenshots
image

### CODE REVIEW

**Comment by benreyn** [comment]
Many of my comments from your other PR (#215) about `let` and `before` apply here as well. Again, these are all just personal preference, and I am happy to get this PR merged as is if you disagree or dont have the time to make the changes I mentioned. 

Again, I REALLY appreciate your work on this!

**Comment by benreyn** [comment]
@EmersonManabuAraki, I think the only blocker here is that we probably shouldnt be adding more controller specs when the prevailing wisdom is to start migrating controller specs to request specs. See #173 , #180 , #172 , #174 for some context, and please let me know if I can be helpful.

**Comment by benreyn** [comment]
@EmersonManabuAraki, are you still actively working on this? Can I be helpful in getting this across the finish line?

**Comment by EmersonManabuAraki** [comment]
I'm not working on it anymore, you can across the finish line

**Comment by sarslanoglu** [comment]
@benreyn What needs to be done in here? I can help

**Comment by benreyn** [comment]
Basically we dont want to keep using controller specs, and want to use request specs moving forward.

**Comment by edwinthinks** [comment]
@EmersonManabuAraki sorry for the delayed response. I'll merge it in and move it over to request to the request spec. LGTM

**Pull request merged**
